package edu.guilford.basicwordle;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class GamePanel extends javax.swing.JPanel {

    // Attributes 
    private static String username;
    private static int winIndicator;
    static String guess;
    private static String correctAnswer = "TESTING"; // base case for sake of beginning analysis
    private static int guessNumber;
    static int[] listLength = {155, 169, 162, 452, 500};
    String[] threeLetterWords = new String[listLength[0]];
    String[] fourLetterWords = new String[listLength[1]];
    String[] fiveLetterWords = new String[listLength[2]];
    String[] sixLetterWords = new String[listLength[3]];
    String[] sevenLetterWords = new String[listLength[4]];
    static String[][] allWords = new String[5][];
    static char[] answer = new char[7];
    static char[] input = new char[7];
    static JLabel[] firstRow = new JLabel[7];
    static JLabel[] secondRow = new JLabel[7];
    static JLabel[] thirdRow = new JLabel[7];
    static JLabel[] fourthRow = new JLabel[7];
    static JLabel[] fifthRow = new JLabel[7];
    static JLabel[] sixthRow = new JLabel[7];
    static JLabel[][] allLabels = new JLabel[6][];
    private static int gameIndicator;
    private static String playerDataString;

    // Imports
    static Random rand = new Random();
    Scanner threeScan = new Scanner(new File(GamePanel.class.getResource("/three_letter_answers.txt").getFile()));
    Scanner fourScan = new Scanner(new File(GamePanel.class.getResource("/four_letter_answers.txt").getFile()));
    Scanner fiveScan = new Scanner(new File(GamePanel.class.getResource("/five_letter_answers.txt").getFile()));
    Scanner sixScan = new Scanner(new File(GamePanel.class.getResource("/six_letter_answers.txt").getFile()));
    Scanner sevenScan = new Scanner(new File(GamePanel.class.getResource("/seven_letter_answers.txt").getFile()));

    public GamePanel() throws FileNotFoundException {
        initComponents();
        defaultVisibility();
        this.setPreferredSize(new Dimension(1000, 1000));
        startGame();
    }

    public JTextField getGuessField() {
        return guessField;
    }

    public void setGuessField(JTextField guessField) {
        this.guessField = guessField;
    }

    public String getGuess() {
        return guess;
    }

    public void setGuess(String guess) {
        GamePanel.guess = guess;
    }

    public static int getGuessNumber() {
        return guessNumber;
    }

    public void setGuessNumber(int guessNumber) {
        GamePanel.guessNumber = guessNumber;
    }

    public static String getCorrectAnswer() {
        return correctAnswer;
    }

    public static void setCorrectAnswer(String correctAnswer) {
        GamePanel.correctAnswer = correctAnswer;
    }

    public static int getGameIndicator() {
        return gameIndicator;
    }

    public static void setGameIndicator(int gameIndicator) {
        GamePanel.gameIndicator = gameIndicator;
    }

    public static String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        GamePanel.username = username;
    }

    public JTextField getUsernameField() {
        return usernameField;
    }

    public void setUsernameField(JTextField usernameField) {
        this.usernameField = usernameField;
    }

    public static int getWinIndicator() {
        return winIndicator;
    }

    public static void setWinIndicator(int winIndicator) {
        GamePanel.winIndicator = winIndicator;
    }

    public JTextArea getPlayerDataTextBox() {
        return playerDataTextBox;
    }

    public void setPlayerDataTextBox(JTextArea playerDataTextBox) {
        this.playerDataTextBox = playerDataTextBox;
    }

    public static String getPlayerDataString() {
        return playerDataString;
    }

    public static void setPlayerDataString(String playerDataString) {
        GamePanel.playerDataString = playerDataString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameSelection = new javax.swing.ButtonGroup();
        guess1char1 = new javax.swing.JLabel();
        guess1char2 = new javax.swing.JLabel();
        guess1char3 = new javax.swing.JLabel();
        guess1char4 = new javax.swing.JLabel();
        guess1char5 = new javax.swing.JLabel();
        guess2char1 = new javax.swing.JLabel();
        guess2char2 = new javax.swing.JLabel();
        guess2char3 = new javax.swing.JLabel();
        guess2char4 = new javax.swing.JLabel();
        guess2char5 = new javax.swing.JLabel();
        guess3char1 = new javax.swing.JLabel();
        guess3char2 = new javax.swing.JLabel();
        guess3char3 = new javax.swing.JLabel();
        guess3char4 = new javax.swing.JLabel();
        guess3char5 = new javax.swing.JLabel();
        guess4char1 = new javax.swing.JLabel();
        guess4char2 = new javax.swing.JLabel();
        guess4char3 = new javax.swing.JLabel();
        guess4char4 = new javax.swing.JLabel();
        guess4char5 = new javax.swing.JLabel();
        guess5char5 = new javax.swing.JLabel();
        guess5char1 = new javax.swing.JLabel();
        guess5char2 = new javax.swing.JLabel();
        guess5char3 = new javax.swing.JLabel();
        guess5char4 = new javax.swing.JLabel();
        guess6char5 = new javax.swing.JLabel();
        guess6char1 = new javax.swing.JLabel();
        guess6char2 = new javax.swing.JLabel();
        guess6char3 = new javax.swing.JLabel();
        guess6char4 = new javax.swing.JLabel();
        guessField = new javax.swing.JTextField();
        guessPrompt = new javax.swing.JLabel();
        guessButton = new javax.swing.JButton();
        guess5char6 = new javax.swing.JLabel();
        guess6char6 = new javax.swing.JLabel();
        guess2char6 = new javax.swing.JLabel();
        guess3char6 = new javax.swing.JLabel();
        guess1char6 = new javax.swing.JLabel();
        guess4char6 = new javax.swing.JLabel();
        guess3char7 = new javax.swing.JLabel();
        guess1char7 = new javax.swing.JLabel();
        guess4char7 = new javax.swing.JLabel();
        guess5char7 = new javax.swing.JLabel();
        guess6char7 = new javax.swing.JLabel();
        guess2char7 = new javax.swing.JLabel();
        sevenGame = new javax.swing.JRadioButton();
        gamePrompt = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        threeGame = new javax.swing.JRadioButton();
        fourGame = new javax.swing.JRadioButton();
        fiveGame = new javax.swing.JRadioButton();
        sixGame = new javax.swing.JRadioButton();
        changePrompt = new javax.swing.JLabel();
        updateGameButton = new javax.swing.JButton();
        resetLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        generatePrompt = new javax.swing.JLabel();
        newWordButton = new javax.swing.JButton();
        cheatLabel = new javax.swing.JLabel();
        viewPlayerData = new javax.swing.JButton();
        playerDataPane = new javax.swing.JScrollPane();
        playerDataTextBox = new javax.swing.JTextArea();

        guess1char1.setBackground(new java.awt.Color(255, 255, 255));
        guess1char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char1.setForeground(new java.awt.Color(255, 255, 255));
        guess1char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char1.setOpaque(true);

        guess1char2.setBackground(new java.awt.Color(255, 255, 255));
        guess1char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char2.setForeground(new java.awt.Color(255, 255, 255));
        guess1char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char2.setOpaque(true);

        guess1char3.setBackground(new java.awt.Color(255, 255, 255));
        guess1char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char3.setForeground(new java.awt.Color(255, 255, 255));
        guess1char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char3.setOpaque(true);

        guess1char4.setBackground(new java.awt.Color(255, 255, 255));
        guess1char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char4.setForeground(new java.awt.Color(255, 255, 255));
        guess1char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char4.setOpaque(true);

        guess1char5.setBackground(new java.awt.Color(255, 255, 255));
        guess1char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char5.setForeground(new java.awt.Color(255, 255, 255));
        guess1char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char5.setOpaque(true);

        guess2char1.setBackground(new java.awt.Color(255, 255, 255));
        guess2char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char1.setForeground(new java.awt.Color(255, 255, 255));
        guess2char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char1.setOpaque(true);

        guess2char2.setBackground(new java.awt.Color(255, 255, 255));
        guess2char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char2.setForeground(new java.awt.Color(255, 255, 255));
        guess2char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char2.setOpaque(true);

        guess2char3.setBackground(new java.awt.Color(255, 255, 255));
        guess2char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char3.setForeground(new java.awt.Color(255, 255, 255));
        guess2char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char3.setOpaque(true);

        guess2char4.setBackground(new java.awt.Color(255, 255, 255));
        guess2char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char4.setForeground(new java.awt.Color(255, 255, 255));
        guess2char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char4.setOpaque(true);

        guess2char5.setBackground(new java.awt.Color(255, 255, 255));
        guess2char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char5.setForeground(new java.awt.Color(255, 255, 255));
        guess2char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char5.setOpaque(true);

        guess3char1.setBackground(new java.awt.Color(255, 255, 255));
        guess3char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char1.setForeground(new java.awt.Color(255, 255, 255));
        guess3char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char1.setOpaque(true);

        guess3char2.setBackground(new java.awt.Color(255, 255, 255));
        guess3char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char2.setForeground(new java.awt.Color(255, 255, 255));
        guess3char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char2.setOpaque(true);

        guess3char3.setBackground(new java.awt.Color(255, 255, 255));
        guess3char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char3.setForeground(new java.awt.Color(255, 255, 255));
        guess3char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char3.setOpaque(true);

        guess3char4.setBackground(new java.awt.Color(255, 255, 255));
        guess3char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char4.setForeground(new java.awt.Color(255, 255, 255));
        guess3char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char4.setOpaque(true);

        guess3char5.setBackground(new java.awt.Color(255, 255, 255));
        guess3char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char5.setForeground(new java.awt.Color(255, 255, 255));
        guess3char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char5.setOpaque(true);

        guess4char1.setBackground(new java.awt.Color(255, 255, 255));
        guess4char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char1.setForeground(new java.awt.Color(255, 255, 255));
        guess4char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char1.setOpaque(true);

        guess4char2.setBackground(new java.awt.Color(255, 255, 255));
        guess4char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char2.setForeground(new java.awt.Color(255, 255, 255));
        guess4char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char2.setOpaque(true);

        guess4char3.setBackground(new java.awt.Color(255, 255, 255));
        guess4char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char3.setForeground(new java.awt.Color(255, 255, 255));
        guess4char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char3.setOpaque(true);

        guess4char4.setBackground(new java.awt.Color(255, 255, 255));
        guess4char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char4.setForeground(new java.awt.Color(255, 255, 255));
        guess4char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char4.setOpaque(true);

        guess4char5.setBackground(new java.awt.Color(255, 255, 255));
        guess4char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char5.setForeground(new java.awt.Color(255, 255, 255));
        guess4char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char5.setOpaque(true);

        guess5char5.setBackground(new java.awt.Color(255, 255, 255));
        guess5char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char5.setForeground(new java.awt.Color(255, 255, 255));
        guess5char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char5.setOpaque(true);

        guess5char1.setBackground(new java.awt.Color(255, 255, 255));
        guess5char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char1.setForeground(new java.awt.Color(255, 255, 255));
        guess5char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char1.setOpaque(true);

        guess5char2.setBackground(new java.awt.Color(255, 255, 255));
        guess5char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char2.setForeground(new java.awt.Color(255, 255, 255));
        guess5char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char2.setOpaque(true);

        guess5char3.setBackground(new java.awt.Color(255, 255, 255));
        guess5char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char3.setForeground(new java.awt.Color(255, 255, 255));
        guess5char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char3.setOpaque(true);

        guess5char4.setBackground(new java.awt.Color(255, 255, 255));
        guess5char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char4.setForeground(new java.awt.Color(255, 255, 255));
        guess5char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char4.setOpaque(true);

        guess6char5.setBackground(new java.awt.Color(255, 255, 255));
        guess6char5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char5.setForeground(new java.awt.Color(255, 255, 255));
        guess6char5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char5.setOpaque(true);

        guess6char1.setBackground(new java.awt.Color(255, 255, 255));
        guess6char1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char1.setForeground(new java.awt.Color(255, 255, 255));
        guess6char1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char1.setOpaque(true);

        guess6char2.setBackground(new java.awt.Color(255, 255, 255));
        guess6char2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char2.setForeground(new java.awt.Color(255, 255, 255));
        guess6char2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char2.setOpaque(true);

        guess6char3.setBackground(new java.awt.Color(255, 255, 255));
        guess6char3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char3.setForeground(new java.awt.Color(255, 255, 255));
        guess6char3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char3.setOpaque(true);

        guess6char4.setBackground(new java.awt.Color(255, 255, 255));
        guess6char4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char4.setForeground(new java.awt.Color(255, 255, 255));
        guess6char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char4.setOpaque(true);

        guessField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        guessField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessFieldActionPerformed(evt);
            }
        });

        guessPrompt.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        guessPrompt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guessPrompt.setText("Enter your guess here!");

        guessButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        guessButton.setText("Guess!");
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        guess5char6.setBackground(new java.awt.Color(255, 255, 255));
        guess5char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char6.setForeground(new java.awt.Color(255, 255, 255));
        guess5char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char6.setOpaque(true);

        guess6char6.setBackground(new java.awt.Color(255, 255, 255));
        guess6char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char6.setForeground(new java.awt.Color(255, 255, 255));
        guess6char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char6.setOpaque(true);

        guess2char6.setBackground(new java.awt.Color(255, 255, 255));
        guess2char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char6.setForeground(new java.awt.Color(255, 255, 255));
        guess2char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char6.setOpaque(true);

        guess3char6.setBackground(new java.awt.Color(255, 255, 255));
        guess3char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char6.setForeground(new java.awt.Color(255, 255, 255));
        guess3char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char6.setOpaque(true);

        guess1char6.setBackground(new java.awt.Color(255, 255, 255));
        guess1char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char6.setForeground(new java.awt.Color(255, 255, 255));
        guess1char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char6.setOpaque(true);

        guess4char6.setBackground(new java.awt.Color(255, 255, 255));
        guess4char6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char6.setForeground(new java.awt.Color(255, 255, 255));
        guess4char6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char6.setOpaque(true);

        guess3char7.setBackground(new java.awt.Color(255, 255, 255));
        guess3char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess3char7.setForeground(new java.awt.Color(255, 255, 255));
        guess3char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess3char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess3char7.setOpaque(true);

        guess1char7.setBackground(new java.awt.Color(255, 255, 255));
        guess1char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess1char7.setForeground(new java.awt.Color(255, 255, 255));
        guess1char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess1char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess1char7.setOpaque(true);

        guess4char7.setBackground(new java.awt.Color(255, 255, 255));
        guess4char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess4char7.setForeground(new java.awt.Color(255, 255, 255));
        guess4char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess4char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess4char7.setOpaque(true);

        guess5char7.setBackground(new java.awt.Color(255, 255, 255));
        guess5char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess5char7.setForeground(new java.awt.Color(255, 255, 255));
        guess5char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess5char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess5char7.setOpaque(true);

        guess6char7.setBackground(new java.awt.Color(255, 255, 255));
        guess6char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess6char7.setForeground(new java.awt.Color(255, 255, 255));
        guess6char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess6char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess6char7.setOpaque(true);

        guess2char7.setBackground(new java.awt.Color(255, 255, 255));
        guess2char7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        guess2char7.setForeground(new java.awt.Color(255, 255, 255));
        guess2char7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guess2char7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        guess2char7.setOpaque(true);

        gameSelection.add(sevenGame);
        sevenGame.setText("7 Letters");
        sevenGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenGameActionPerformed(evt);
            }
        });

        gamePrompt.setText("Select your game!");

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Enter your username (no spaces), then press ENTER!");

        gameSelection.add(threeGame);
        threeGame.setText("3 Letters");
        threeGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeGameActionPerformed(evt);
            }
        });

        gameSelection.add(fourGame);
        fourGame.setText("4 Letters");
        fourGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourGameActionPerformed(evt);
            }
        });

        gameSelection.add(fiveGame);
        fiveGame.setText("5 Letters");
        fiveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveGameActionPerformed(evt);
            }
        });

        gameSelection.add(sixGame);
        sixGame.setText("6 Letters");
        sixGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixGameActionPerformed(evt);
            }
        });

        changePrompt.setText("Once you've selected...");

        updateGameButton.setText("CLICK HERE!");
        updateGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGameButtonActionPerformed(evt);
            }
        });

        resetLabel.setText("Clicked too soon?");

        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        generatePrompt.setText("Generate a new word!");

        newWordButton.setText("NEW WORD");
        newWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWordButtonActionPerformed(evt);
            }
        });

        cheatLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cheatLabel.setText("temp");

        viewPlayerData.setText("Play the game, then view your data!");
        viewPlayerData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlayerDataActionPerformed(evt);
            }
        });

        playerDataTextBox.setColumns(20);
        playerDataTextBox.setRows(5);
        playerDataTextBox.setText("Once the game is finished,\npress the button and then\nyour data will be displayed\nin this box!");
        playerDataPane.setViewportView(playerDataTextBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess1char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess1char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess1char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess1char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess1char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess2char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess2char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess2char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess2char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess2char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess3char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess3char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess3char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess3char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess3char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess4char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess4char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess4char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess4char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess4char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess5char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess5char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess5char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess5char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess5char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess6char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess6char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess6char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess6char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(guess6char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guess1char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess2char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess3char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess4char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess5char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess6char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guess1char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guess2char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guess3char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameField)
                                    .addComponent(threeGame)
                                    .addComponent(gamePrompt)
                                    .addComponent(sixGame)
                                    .addComponent(sevenGame)
                                    .addComponent(changePrompt)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fourGame)
                                        .addComponent(fiveGame))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guess5char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guess6char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(generatePrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewPlayerData)
                                    .addComponent(playerDataPane, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guess4char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(resetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guessPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guessField)
                            .addComponent(guessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(cheatLabel)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess1char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess1char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess1char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess1char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess1char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess2char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess2char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess2char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess2char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess2char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess3char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess3char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess3char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess3char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess3char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess4char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess4char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess4char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess4char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess4char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess5char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess5char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess5char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess5char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess5char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guess6char1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess6char2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess6char3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess6char4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guess6char5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guessPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guessButton)
                            .addComponent(cheatLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guess1char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess2char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess3char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess4char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess5char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess6char6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guess1char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess2char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess3char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess4char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess5char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(guess6char7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gamePrompt)
                        .addGap(8, 8, 8)
                        .addComponent(threeGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sixGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sevenGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changePrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generatePrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newWordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewPlayerData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playerDataPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(523, 523, 523))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        guessEntered();
    }//GEN-LAST:event_guessButtonActionPerformed

    private void sevenGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenGameActionPerformed
        setGameIndicator(7);
    }//GEN-LAST:event_sevenGameActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        usernameLabel.setText("Thanks! Continue below.");
        username = (usernameField.getText().substring(0, 1).toUpperCase() + usernameField.getText().substring(1).toLowerCase());
        System.out.println(username);
        usernameField.setText(username);
        threeGame.setVisible(true);
        fourGame.setVisible(true);
        fiveGame.setVisible(true);
        sixGame.setVisible(true);
        sevenGame.setVisible(true);
        gamePrompt.setVisible(true);
        changePrompt.setVisible(true);
        updateGameButton.setVisible(true);
        resetLabel.setVisible(true);
        resetButton.setVisible(true);
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void threeGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeGameActionPerformed
        setGameIndicator(3);
    }//GEN-LAST:event_threeGameActionPerformed

    private void fourGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourGameActionPerformed
        setGameIndicator(4);
    }//GEN-LAST:event_fourGameActionPerformed

    private void fiveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveGameActionPerformed
        setGameIndicator(5);
    }//GEN-LAST:event_fiveGameActionPerformed

    private void sixGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixGameActionPerformed
        setGameIndicator(6);
    }//GEN-LAST:event_sixGameActionPerformed

    private void updateGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGameButtonActionPerformed
        if (threeGame.isSelected() || fourGame.isSelected() || fiveGame.isSelected() || sixGame.isSelected() || sevenGame.isSelected()) {
            updateGameSelection();
            generatePrompt.setVisible(true);
            newWordButton.setVisible(true);
            updateGameButton.setText("CLICK HERE!");
            cheatLabel.setVisible(false);
        } else {
            updateGameButton.setText("Select a game!");
        }
    }//GEN-LAST:event_updateGameButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        cheatLabel.setVisible(false);
        setGuessNumber(0);
        for (int i = 0; i < 7; i++) {
            allLabels[0][i].setVisible(true);
            allLabels[1][i].setVisible(true);
            allLabels[2][i].setVisible(true);
            allLabels[3][i].setVisible(true);
            allLabels[4][i].setVisible(true);
            allLabels[5][i].setVisible(true);
        }
        resetLabelDisplay();
        newWordButton.setVisible(false);
        generatePrompt.setVisible(false);
        guessPrompt.setText("Enter your guess here!");
        guessButton.setText("Guess!");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void newWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWordButtonActionPerformed
        generateWord();
        cheatLabel.setVisible(false);
        guessPrompt.setVisible(true);
        guessField.setVisible(true);
        guessButton.setVisible(true);
        setGuessNumber(0);
        resetLabelDisplay();
        cheatLabel.setText("Correct Answer: " + correctAnswer);
        guessPrompt.setText("Enter your guess here!");
        guessButton.setText("Guess!");
    }//GEN-LAST:event_newWordButtonActionPerformed

    private void guessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessFieldActionPerformed
        guessEntered();
    }//GEN-LAST:event_guessFieldActionPerformed

    private void viewPlayerDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlayerDataActionPerformed
        // TODO add your handling code here:
        getPlayerDataString();
        playerDataTextBox.setText(playerDataString);
    }//GEN-LAST:event_viewPlayerDataActionPerformed

    public static boolean DisplayColorLetters(char[] inputWord, char[] correctWord) {
        boolean correct = true;
        char[] answerTemp = Arrays.copyOf(correctWord, getGameIndicator());;
        int[] colorForLetter = new int[getGameIndicator()]; //0 is grey, yellow is 1, green is 2

        for (int i = 0; i < getGameIndicator(); i++) { //check for any correct position+letter (green)
            if (inputWord[i] == answerTemp[i]) {
                answerTemp[i] = '-';
                colorForLetter[i] = 2;
            } else {
                correct = false;
            }
        }

        for (int j = 0; j < getGameIndicator(); j++) { //check for any correct letter (yellow)
            for (int k = 0; k < getGameIndicator(); k++) {
                if (inputWord[j] == answerTemp[k] && colorForLetter[j] != 2) {
                    //if that letter is not already green and matches some other letter
                    colorForLetter[j] = 1;
                    answerTemp[k] = '-';
                }
            }
        }

        for (int m = 0; m < getGameIndicator(); m++) {
            if (colorForLetter[m] == 0) {
                allLabels[getGuessNumber()][m].setBackground(new Color(120, 124, 127));
            }
            if (colorForLetter[m] == 1) {
                allLabels[getGuessNumber()][m].setBackground(new Color(200, 182, 83));
            }
            if (colorForLetter[m] == 2) {
                allLabels[getGuessNumber()][m].setBackground(new Color(108, 169, 101));
            }
        }

        return correct;
    }

    private static void updateGameSelection() {
        int indicator = getGameIndicator();
        for (int i = indicator; i < 7; i++) {
            allLabels[0][i].setVisible(false);
            allLabels[1][i].setVisible(false);
            allLabels[2][i].setVisible(false);
            allLabels[3][i].setVisible(false);
            allLabels[4][i].setVisible(false);
            allLabels[5][i].setVisible(false);
        }
    }

    private static void generateWord() {
        int indicator = getGameIndicator();
        correctAnswer = (allWords[indicator - 3][rand.nextInt(listLength[indicator - 3])]);
        for (int k = 0; k < indicator; k++) {
            answer[k] = correctAnswer.toUpperCase().charAt(k);
        }
    }

    public void UpdatePlayerData() {
        // All other code is done within the class "GameUser.java"

        GameUser user = new GameUser(username);
        user.setUsername(username);
        user.PlayerFileManager();

    }

    public void defaultVisibility() {

        cheatLabel.setVisible(false);
        threeGame.setVisible(false);
        fourGame.setVisible(false);
        fiveGame.setVisible(false);
        sixGame.setVisible(false);
        sevenGame.setVisible(false);
        gamePrompt.setVisible(false);
        newWordButton.setVisible(false);
        generatePrompt.setVisible(false);
        changePrompt.setVisible(false);
        updateGameButton.setVisible(false);
        resetLabel.setVisible(false);
        resetButton.setVisible(false);
        guessPrompt.setVisible(false);
        guessField.setVisible(false);
        guessButton.setVisible(false);
    }

    public void startGame() {
        guessNumber = 0;

        // Assigning wordsets to the word list array
        allWords[0] = threeLetterWords;
        allWords[1] = fourLetterWords;
        allWords[2] = fiveLetterWords;
        allWords[3] = sixLetterWords;
        allWords[4] = sevenLetterWords;

        // Assigning all labels to rows, and each charachter to a label
        allLabels[0] = firstRow;
        allLabels[1] = secondRow;
        allLabels[2] = thirdRow;
        allLabels[3] = fourthRow;
        allLabels[4] = fifthRow;
        allLabels[5] = sixthRow;

        firstRow[0] = guess1char1;
        firstRow[1] = guess1char2;
        firstRow[2] = guess1char3;
        firstRow[3] = guess1char4;
        firstRow[4] = guess1char5;
        firstRow[5] = guess1char6;
        firstRow[6] = guess1char7;

        secondRow[0] = guess2char1;
        secondRow[1] = guess2char2;
        secondRow[2] = guess2char3;
        secondRow[3] = guess2char4;
        secondRow[4] = guess2char5;
        secondRow[5] = guess2char6;
        secondRow[6] = guess2char7;

        thirdRow[0] = guess3char1;
        thirdRow[1] = guess3char2;
        thirdRow[2] = guess3char3;
        thirdRow[3] = guess3char4;
        thirdRow[4] = guess3char5;
        thirdRow[5] = guess3char6;
        thirdRow[6] = guess3char7;

        fourthRow[0] = guess4char1;
        fourthRow[1] = guess4char2;
        fourthRow[2] = guess4char3;
        fourthRow[3] = guess4char4;
        fourthRow[4] = guess4char5;
        fourthRow[5] = guess4char6;
        fourthRow[6] = guess4char7;

        fifthRow[0] = guess5char1;
        fifthRow[1] = guess5char2;
        fifthRow[2] = guess5char3;
        fifthRow[3] = guess5char4;
        fifthRow[4] = guess5char5;
        fifthRow[5] = guess5char6;
        fifthRow[6] = guess5char7;

        sixthRow[0] = guess6char1;
        sixthRow[1] = guess6char2;
        sixthRow[2] = guess6char3;
        sixthRow[3] = guess6char4;
        sixthRow[4] = guess6char5;
        sixthRow[5] = guess6char6;
        sixthRow[6] = guess6char7;

        // Grabbing files
        int index = 0;
        while (threeScan.hasNext()) { // get three letter answers
            threeLetterWords[index] = threeScan.next().toUpperCase();
            index = index + 1;
        }

        index = 0;
        while (fourScan.hasNext()) { // get four letter answers
            fourLetterWords[index] = fourScan.next().toUpperCase();
            index = index + 1;
        }

        index = 0;
        while (fiveScan.hasNext()) { // get five letter answers
            fiveLetterWords[index] = fiveScan.next().toUpperCase();
            index = index + 1;
        }

        index = 0;
        while (sixScan.hasNext()) { // get six letter answers
            sixLetterWords[index] = sixScan.next().toUpperCase();
            index = index + 1;
        }

        index = 0;
        while (sevenScan.hasNext()) { // get seven letter answers
            sevenLetterWords[index] = sevenScan.next().toUpperCase();
            index = index + 1;
        }

    }

    public void guessEntered() {
        cheatLabel.setVisible(false);
        guess = guessField.getText(); // gets guess value from field

        if (guess.length() != getGameIndicator()) {
            guessPrompt.setText("Enter a " + getGameIndicator() + " letter word.");
        } else if (getGuessNumber() >= 6 || guess == getCorrectAnswer()) {
        } else {
            for (int i = 0; i < gameIndicator; i++) {
                input[i] = guess.toUpperCase().charAt(i);
            }// assigns guess to []

            for (int l = 0; l < getGameIndicator(); l++) {
                allLabels[getGuessNumber()][l].setText(Character.toString(input[l]));
            }
            if (DisplayColorLetters(input, answer)) {
                guessPrompt.setText("Congratulations, you win!");
                guessButton.setText("You found the correct word =>");
                viewPlayerData.setText("View your data!");
                playerDataTextBox.setVisible(true);
                cheatLabel.setVisible(true);
                winIndicator = 1;
                UpdatePlayerData();
                getPlayerDataString();
                playerDataTextBox.setText(playerDataString);
            } else if (guessNumber > 4) {

                guessPrompt.setText("Sorry, try again next time.");
                guessButton.setText("Here's the correct word =>");
                viewPlayerData.setText("View your data!");
                playerDataTextBox.setVisible(true);
                cheatLabel.setVisible(true);
                winIndicator = 0;
                UpdatePlayerData();
                getPlayerDataString();
                playerDataTextBox.setText(playerDataString);
            }
            guessNumber = guessNumber + 1;
        }
        guessField.setText("");
    }

    public void resetLabelDisplay() {
        for (int i = 0; i < 7; i++) {
            allLabels[0][i].setText("");
            allLabels[1][i].setText("");
            allLabels[2][i].setText("");
            allLabels[3][i].setText("");
            allLabels[4][i].setText("");
            allLabels[5][i].setText("");
        }
        for (int k = 0; k < 7; k++) {
            allLabels[0][k].setBackground(Color.WHITE);
            allLabels[1][k].setBackground(Color.WHITE);
            allLabels[2][k].setBackground(Color.WHITE);
            allLabels[3][k].setBackground(Color.WHITE);
            allLabels[4][k].setBackground(Color.WHITE);
            allLabels[5][k].setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePrompt;
    private javax.swing.JLabel cheatLabel;
    private javax.swing.JRadioButton fiveGame;
    private javax.swing.JRadioButton fourGame;
    private javax.swing.JLabel gamePrompt;
    private javax.swing.ButtonGroup gameSelection;
    private javax.swing.JLabel generatePrompt;
    private javax.swing.JLabel guess1char1;
    private javax.swing.JLabel guess1char2;
    private javax.swing.JLabel guess1char3;
    private javax.swing.JLabel guess1char4;
    private javax.swing.JLabel guess1char5;
    private javax.swing.JLabel guess1char6;
    private javax.swing.JLabel guess1char7;
    private javax.swing.JLabel guess2char1;
    private javax.swing.JLabel guess2char2;
    private javax.swing.JLabel guess2char3;
    private javax.swing.JLabel guess2char4;
    private javax.swing.JLabel guess2char5;
    private javax.swing.JLabel guess2char6;
    private javax.swing.JLabel guess2char7;
    private javax.swing.JLabel guess3char1;
    private javax.swing.JLabel guess3char2;
    private javax.swing.JLabel guess3char3;
    private javax.swing.JLabel guess3char4;
    private javax.swing.JLabel guess3char5;
    private javax.swing.JLabel guess3char6;
    private javax.swing.JLabel guess3char7;
    private javax.swing.JLabel guess4char1;
    private javax.swing.JLabel guess4char2;
    private javax.swing.JLabel guess4char3;
    private javax.swing.JLabel guess4char4;
    private javax.swing.JLabel guess4char5;
    private javax.swing.JLabel guess4char6;
    private javax.swing.JLabel guess4char7;
    private javax.swing.JLabel guess5char1;
    private javax.swing.JLabel guess5char2;
    private javax.swing.JLabel guess5char3;
    private javax.swing.JLabel guess5char4;
    private javax.swing.JLabel guess5char5;
    private javax.swing.JLabel guess5char6;
    private javax.swing.JLabel guess5char7;
    private javax.swing.JLabel guess6char1;
    private javax.swing.JLabel guess6char2;
    private javax.swing.JLabel guess6char3;
    private javax.swing.JLabel guess6char4;
    private javax.swing.JLabel guess6char5;
    private javax.swing.JLabel guess6char6;
    private javax.swing.JLabel guess6char7;
    private javax.swing.JButton guessButton;
    private javax.swing.JTextField guessField;
    private javax.swing.JLabel guessPrompt;
    private javax.swing.JButton newWordButton;
    private javax.swing.JScrollPane playerDataPane;
    private javax.swing.JTextArea playerDataTextBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel resetLabel;
    private javax.swing.JRadioButton sevenGame;
    private javax.swing.JRadioButton sixGame;
    private javax.swing.JRadioButton threeGame;
    private javax.swing.JButton updateGameButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton viewPlayerData;
    // End of variables declaration//GEN-END:variables

}
